### ISSUE TITLE
✨ Implement login user page

### ISSUE THREAD

**Issue by trankhacbinhduong** [trankhacbinhduong/hithaui#1]
**TODO LIST**
- [x] implement blank layout UI
- [x] setup pinia auth store
- [x] implement login layout UI
- [x] integrate login user API
